[package]
name = "alluno-vdd-sys"
version = "1.2.0"
edition = "2021"
description = "Rust bindings for Alluno Virtual Display Driver (AllunoVDD)"
license = "MIT"

[[bin]]
name = "alluno-vdd-test"
path = "src/bin/test.rs"

[dependencies]
windows = { version = "0.62.2", features = [
    "Win32_Foundation",
    "Win32_System_IO",
    "Win32_Storage_FileSystem",
    "Win32_Devices_DeviceAndDriverInstallation",
    "Win32_Devices_Display",
    "Win32_Graphics_Gdi",
    "Win32_Security",
    "Win32_System_Com",
    "Win32_System_Console",
    "Win32_UI_WindowsAndMessaging",
] }
