name: CI/CD

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  cicd:
    name: CI/CD
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy

      - name: Format check
        run: cargo fmt --check

      - name: Clippy
        run: cargo clippy -- -D warnings

      - name: Test
        run: cargo test -- --nocapture

      - name: Build
        if: |
          github.ref == 'refs/heads/master' &&
          !contains(github.event.head_commit.message, 'chore')
        run: cargo build --release

      - name: Get version
        if: |
          github.ref == 'refs/heads/master' &&
          !contains(github.event.head_commit.message, 'chore')
        id: version
        shell: bash
        run: echo "version=$(cargo metadata --no-deps --format-version 1 | jq -r '.packages[0].version')" >> $GITHUB_OUTPUT

      - name: Upload binaries
        if: |
          github.ref == 'refs/heads/master' &&
          !contains(github.event.head_commit.message, 'chore')
        uses: actions/upload-artifact@v4
        with:
          name: alluno-vdd-sys
          path: target/release/*.exe
          retention-days: 1

      - name: Create release
        if: |
          github.ref == 'refs/heads/master' &&
          !contains(github.event.head_commit.message, 'chore')
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.version.outputs.version }}
          name: v${{ steps.version.outputs.version }}
          files: target/release/*.exe
          generate_release_notes: true
          make_latest: true
